# Generated by Django 4.2 on 2025-04-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('canceled', 'Cancelado'), ('sent', 'Enviado')], default='pending', max_length=10),
        ),
    ]
