# Generated by Django 4.2 on 2025-04-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('canceled', 'Cancelado'), ('delivered', 'Enviado')], default='pending', max_length=10),
        ),
    ]
