# Generated by Django 4.2 on 2025-05-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_delivery_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
