# Generated by Django 4.2 on 2025-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_delivery_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
