# Generated by Django 4.2 on 2025-05-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_delivery_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('canceled', 'Cancelado'), ('delivered', 'Enviado')], max_length=10, null=True),
        ),
    ]
