# Generated by Django 4.2 on 2025-05-21 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_remove_cakeflavor_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cakeflavor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sabor de Pastel', 'verbose_name_plural': 'Sabores de Pastel'},
        ),
        migrations.AlterModelOptions(
            name='cakesize',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tamaño de Pastel', 'verbose_name_plural': 'Tamaños de Pastel'},
        ),
        migrations.AddField(
            model_name='cakesize',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cakesize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cakeflavor',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
